package testDB;

import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.io.File;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */



public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
	SVcheck temp;
	private String user;
	private String pwd;
	public void getMainPage()
	{
		if(user.compareTo("giaovu")==0)
			mainpage.setVisible(true);
		else
			mainpage2.setVisible(true);
	}
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        loginpage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        username = new javax.swing.JTextField();
        login = new javax.swing.JButton();
        mainpage = new javax.swing.JPanel();
        logout = new javax.swing.JButton();
        addSV = new javax.swing.JButton();
        ScheduleWatch = new javax.swing.JButton();
        staticstic = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        changePassword = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        mainpage2 = new javax.swing.JPanel();
        logout1 = new javax.swing.JButton();
        changePassword1 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        changePasswordpage = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        oldPassword = new javax.swing.JTextField();
        newPassword = new javax.swing.JTextField();
        repeatNewPassword = new javax.swing.JTextField();
        confirmChange = new javax.swing.JButton();
        comeback = new javax.swing.JButton();
        comeback1 = new javax.swing.JButton();
        comeback2 = new javax.swing.JButton();
        comeback3 = new javax.swing.JButton();
        comeback4 = new javax.swing.JButton();
        comeback5 = new javax.swing.JButton();
        searchClasspage = new javax.swing.JPanel();
        searchClassSchedule = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        watchSchedule = new javax.swing.JTable();
        classField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        Schedulepage = new javax.swing.JPanel();
        searchClass = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        classField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        addSVpage = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        addSVBtn = new javax.swing.JButton();
        importList = new javax.swing.JButton();
        importpage = new javax.swing.JPanel();
        chooseImport = new javax.swing.JComboBox<>();
        confirmChoice = new javax.swing.JButton();
        confirmFileChoice = new javax.swing.JButton();
        filePath = new javax.swing.JFileChooser();
        searchGradepage = new javax.swing.JPanel();
        searchClassGrade = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        watchGrade = new javax.swing.JTable();
        classField3 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        comeback5 = new javax.swing.JButton();
        GradeWatch = new javax.swing.JButton();
        SVPKpage = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        MssvField = new javax.swing.JTextField();
        NameField = new javax.swing.JTextField();
        subjectField = new javax.swing.JTextField();
        pointField = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        pkBtn = new javax.swing.JButton();
        comeback6 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        wantedPointField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        reason = new javax.swing.JTextField();
        PKpage = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        comeback7 = new javax.swing.JButton();
        searchSVGradepage = new javax.swing.JPanel();
        searchSVGrade = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        watchGradeSV = new javax.swing.JTable();
        subJectSearchFIeld = new javax.swing.JTextField();
        jLabelM = new javax.swing.JLabel();
        comeback8 = new javax.swing.JButton();
        staticsticpage = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        comeback9 = new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "STT", "MSSV", "Họ và tên", "Môn học", "Cột điểm", "Điểm mong muốn", "Lý do", "Trạng thái"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
            jScrollPane8.setViewportView(jTable4);

            comeback9.setText("Quay lại");
            comeback9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comeback9ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout staticsticpageLayout = new javax.swing.GroupLayout(staticsticpage);
            staticsticpage.setLayout(staticsticpageLayout);
            staticsticpageLayout.setHorizontalGroup(
                staticsticpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(staticsticpageLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(staticsticpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(comeback9)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            staticsticpageLayout.setVerticalGroup(
                staticsticpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staticsticpageLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(comeback9)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
        searchSVGrade.setText("Tìm kiếm");
        searchSVGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchSVGradeActionPerformed(evt);
            }
        });

        watchGradeSV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Họ tên", "Điểm GK", "Điểm CK", "Điểm cộng", "Điểm tổng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(watchGradeSV);
        
        

        jLabelM.setText("Lớp");

        comeback8.setText("Quay lại");
       
        comeback8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeback8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchSVGradepageLayout = new javax.swing.GroupLayout(searchSVGradepage);
        searchSVGradepage.setLayout(searchSVGradepageLayout);
        searchSVGradepageLayout.setHorizontalGroup(
            searchSVGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSVGradepageLayout.createSequentialGroup()
                .addGroup(searchSVGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchSVGradepageLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabelM, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(subJectSearchFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(searchSVGrade))
                    .addComponent(comeback8))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchSVGradepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchSVGradepageLayout.setVerticalGroup(
            searchSVGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchSVGradepageLayout.createSequentialGroup()
                .addComponent(comeback8)
                .addGap(27, 27, 27)
                .addGroup(searchSVGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchSVGrade)
                    .addComponent(subJectSearchFIeld, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelM, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {
                    "STT", "MSSV", "Họ tên", "Môn", "Cột ", "Điểm mong muốn", "Lý do", "Trạng thái"
                }));
            
            jScrollPane5.setViewportView(jTable3);
           
            comeback7.setText("Quay lại");
            comeback7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    comeback7ActionPerformed(evt);
                }
            });
            javax.swing.GroupLayout PKpageLayout = new javax.swing.GroupLayout(PKpage);
            PKpage.setLayout(PKpageLayout);
            PKpageLayout.setHorizontalGroup(
                PKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PKpageLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(PKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PKpageLayout.createSequentialGroup()
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGap(23, 23, 23))
                        .addGroup(PKpageLayout.createSequentialGroup()
                            .addComponent(comeback7)
                            .addContainerGap(309, Short.MAX_VALUE))))
            );
            PKpageLayout.setVerticalGroup(
                PKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PKpageLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(comeback7)
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(22, Short.MAX_VALUE))
            );
        
        
        jLabel18.setText("Tên");

        jLabel19.setText("MSSV");

        jLabel20.setText("Môn");

        jLabel21.setText("Cột điểm phúc khảo");

      
        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Phúc khảo");

        pkBtn.setText("Nộp");
        pkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pkBtnActionPerformed(evt);
            }
        });

        comeback6.setText("Quay lại");
      
        comeback6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	
                comeback6ActionPerformed(evt);
            }
        });

        jLabel23.setText("Điểm mong muốn");

        jLabel24.setText("Lý do");

        javax.swing.GroupLayout SVPKpageLayout = new javax.swing.GroupLayout(SVPKpage);
        SVPKpage.setLayout(SVPKpageLayout);
        SVPKpageLayout.setHorizontalGroup(
            SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SVPKpageLayout.createSequentialGroup()
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SVPKpageLayout.createSequentialGroup()
                        .addComponent(comeback6)
                        .addGap(74, 74, 74))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SVPKpageLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23)
                            .addComponent(jLabel20)
                            .addComponent(jLabel24))
                        .addGap(41, 41, 41)))
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MssvField)
                        .addComponent(NameField)
                        .addComponent(subjectField)
                        .addComponent(pointField)
                        .addComponent(wantedPointField))
                    .addComponent(reason, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SVPKpageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pkBtn)
                .addGap(132, 132, 132))
        );
        SVPKpageLayout.setVerticalGroup(
            SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SVPKpageLayout.createSequentialGroup()
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SVPKpageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comeback6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MssvField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pointField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(wantedPointField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(SVPKpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SVPKpageLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(reason, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pkBtn)
                .addContainerGap())
        );
        GradeWatch.setText("Xem điểm");
        GradeWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GradeWatchActionPerformed(evt);
            }});
        
        
        searchClassGrade.setText("Tìm kiếm");
        searchClassGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClassGradeActionPerformed(evt);
            }
        });

        watchGrade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "MSSV", "Họ tên", "Điểm GK", "Điểm CK", "Điểm cộng", "Điểm tổng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(watchGrade);

       

        jLabel17.setText("Lớp");

        comeback5.setText("Quay lại");
        
        comeback5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeback5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchGradepageLayout = new javax.swing.GroupLayout(searchGradepage);
        searchGradepage.setLayout(searchGradepageLayout);
        searchGradepageLayout.setHorizontalGroup(
            searchGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchGradepageLayout.createSequentialGroup()
                .addGroup(searchGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchGradepageLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(classField3, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59)
                        .addComponent(searchClassGrade))
                    .addComponent(comeback5))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchGradepageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
        );
        searchGradepageLayout.setVerticalGroup(
            searchGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchGradepageLayout.createSequentialGroup()
                .addComponent(comeback5)
                .addGap(27, 27, 27)
                .addGroup(searchGradepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchClassGrade)
                    .addComponent(classField3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62))
        );
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        chooseImport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Danh sách lớp", "Bảng điểm", "Thời khóa biểu" }));

        confirmChoice.setText("Chọn");
        confirmChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmChoiceActionPerformed(evt);
            }
        });
        confirmFileChoice.setText("Xác nhận");
        confirmFileChoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmFileChoiceActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout importpageLayout = new javax.swing.GroupLayout(importpage);
        importpage.setLayout(importpageLayout);
       
        importpage.setLayout(importpageLayout);
        importpageLayout.setHorizontalGroup(
            importpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importpageLayout.createSequentialGroup()
                .addGroup(importpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(importpageLayout.createSequentialGroup()
                        .addGap(172, 172, 172)
                       
                        
                        .addComponent(confirmFileChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(importpageLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(chooseImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmChoice)))
                	.addComponent(comeback4)
                .addContainerGap(277, Short.MAX_VALUE))
        );
        importpageLayout.setVerticalGroup(
            importpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(importpageLayout.createSequentialGroup()
            	.addComponent(comeback4)
                .addGap(88, 88, 88)
                .addGroup(importpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chooseImport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmChoice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(confirmFileChoice, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

       
       
        

        //setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Tài khoản");

        jLabel4.setText("Mật khẩu");

       /* password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });*/

        login.setText("Đăng nhập");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginpageLayout = new javax.swing.GroupLayout(loginpage);
        loginpage.setLayout(loginpageLayout);
        loginpageLayout.setHorizontalGroup(
            loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpageLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(37, 37, 37)
                .addGroup(loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(password)
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                    .addGroup(loginpageLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(login)))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        loginpageLayout.setVerticalGroup(
            loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginpageLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(loginpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login)
                .addContainerGap(170, Short.MAX_VALUE))
        );

        logout.setText("Đăng xuất");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        addSV.setText("Thêm sinh viên");
        addSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSVActionPerformed(evt);
            }
        });

        ScheduleWatch.setText("Xem thời khóa biểu");
        ScheduleWatch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleWatchActionPerformed(evt);
            }
        });

        staticstic.setText("Thống kê");
        staticstic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staticsticActionPerformed(evt);
            }
        });

        jButton2.setText("Xem danh sách lớp");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        changePassword.setText("Đổi mật khẩu");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	changePasswordActionPerformed(evt);
            }
        });
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Trang chủ");

        jLabel2.setText("chào");
        importList.setText("Import từ file");
        importList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                importListActionPerformed(evt);
            }
        });
        jButton6.setText("Xem phúc khảo");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpageLayout = new javax.swing.GroupLayout(mainpage);
        mainpage.setLayout(mainpageLayout);
        mainpageLayout.setHorizontalGroup(
            mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout))
            .addGroup(mainpageLayout.createSequentialGroup()
                .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainpageLayout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        	.addComponent(importList, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)	
                            .addComponent(ScheduleWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GradeWatch, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addSV, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(staticstic, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(changePassword, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(mainpageLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        mainpageLayout.setVerticalGroup(
            mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpageLayout.createSequentialGroup()
                .addGroup(mainpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logout)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleWatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GradeWatch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(importList)
            	.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staticstic)
                .addGap(5, 5, 5)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePassword)
                .addGap(37, 37, 37))
            	
        );

        logout1.setText("Đăng xuất");
        logout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        changePassword1.setText("Đổi mật khẩu");
       
        changePassword1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	mainpage2.setVisible(false);
                changePasswordActionPerformed(evt);
            }

			
        });

        jButton8.setText("Xem bảng điểm");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Trang chủ");

        jLabel9.setText("chào");

        jButton9.setText("Xem thời khóa biểu");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton5.setText("Phúc khảo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainpage2Layout = new javax.swing.GroupLayout(mainpage2);
        mainpage2.setLayout(mainpage2Layout);
        mainpage2Layout.setHorizontalGroup(
            mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainpage2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout1))
            .addGroup(mainpage2Layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addGroup(mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changePassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(162, Short.MAX_VALUE))
            .addGroup(mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainpage2Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addGroup(mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainpage2Layout.createSequentialGroup()
                            .addGap(32, 32, 32)
                            .addGroup(mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                                .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(127, Short.MAX_VALUE)))
        );
        mainpage2Layout.setVerticalGroup(
            mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpage2Layout.createSequentialGroup()
                .addGroup(mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logout1)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePassword1)
                .addGap(83, 83, 83))
            .addGroup(mainpage2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainpage2Layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                    .addComponent(jButton8)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton9)
                    .addGap(142, 142, 142)))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Mật khẩu cũ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nhập mật khẩu mới");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Nhập lại mật khẩu mới");

       
       

        confirmChange.setText("Đồng ý");
        confirmChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	confirmChangeMouseClicked(evt);
            }
        });

        comeback.setText("Quay lại");
        comeback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comebackActionPerformed(evt);
            }
        });
       /* comeback.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comebackMouseClicked(evt);
            }
        });*/

        javax.swing.GroupLayout changePasswordpageLayout = new javax.swing.GroupLayout(changePasswordpage);
        changePasswordpage.setLayout(changePasswordpageLayout);
        changePasswordpageLayout.setHorizontalGroup(
            changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordpageLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(24, 24, 24)
                .addGroup(changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(oldPassword)
                    .addComponent(newPassword)
                    .addComponent(repeatNewPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                .addContainerGap(71, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, changePasswordpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmChange)
                .addGap(97, 97, 97))
            .addGroup(changePasswordpageLayout.createSequentialGroup()
                .addComponent(comeback)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        changePasswordpageLayout.setVerticalGroup(
            changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePasswordpageLayout.createSequentialGroup()
                .addComponent(comeback)
                .addGap(51, 51, 51)
                .addGroup(changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePasswordpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(repeatNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(confirmChange)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        searchClassSchedule.setText("Tìm kiếm");
        searchClassSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClassScheduleActionPerformed(evt);
            }
        });

        watchSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                
            },
            new String [] {
                "STT", "Mã môn", "Tên môn", "Phòng học"
            }
        ) {
            
            boolean[] canEdit = new boolean [] {
                true, true, true, true
            };

           

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                    {null, null, null, null, null},
                    
                },
                new String [] {
                    "STT", "MSSV", "Họ và tên", "Giới tính", "CMND"
                }
            ) {
                Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
                };

                public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
                }
            });
        jScrollPane2.setViewportView(watchSchedule);

        /*classField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classField1ActionPerformed(evt);
            }
        });*/

        jLabel10.setText("Lớp");

        comeback1.setText("Quay lại");
        comeback1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeback1ActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout searchClasspageLayout = new javax.swing.GroupLayout(searchClasspage);
        searchClasspage.setLayout(searchClasspageLayout);
        searchClasspageLayout.setHorizontalGroup(
            searchClasspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchClasspageLayout.createSequentialGroup()
                .addGroup(searchClasspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(searchClasspageLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(searchClasspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(searchClasspageLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(classField1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(searchClass))))
                    .addComponent(comeback1))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        searchClasspageLayout.setVerticalGroup(
            searchClasspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchClasspageLayout.createSequentialGroup()
                .addComponent(comeback1)
                .addGap(27, 27, 27)
                .addGroup(searchClasspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchClass)
                    .addComponent(classField1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        searchClass.setText("Tìm kiếm");
        searchClass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchClassActionPerformed(evt);
            }
        });

      
        jScrollPane3.setViewportView(jTable2);

        /*classField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classField2ActionPerformed(evt);
            }
        });*/

        jLabel11.setText("Lớp");

        comeback3.setText("Quay lại");
       /* comeback3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comebackMouseClicked(evt);
            }
        });*/
        comeback3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeback3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SchedulepageLayout = new javax.swing.GroupLayout(Schedulepage);
        Schedulepage.setLayout(SchedulepageLayout);
        SchedulepageLayout.setHorizontalGroup(
            SchedulepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchedulepageLayout.createSequentialGroup()
                .addGroup(SchedulepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SchedulepageLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(SchedulepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SchedulepageLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(classField2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(searchClassSchedule))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(comeback3))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        SchedulepageLayout.setVerticalGroup(
            SchedulepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SchedulepageLayout.createSequentialGroup()
                .addComponent(comeback3)
                .addGap(27, 27, 27)
                .addGroup(SchedulepageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchClassSchedule)
                    .addComponent(classField2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );

        jLabel12.setText("Tên");

        jLabel13.setText("MSSV");

        jLabel14.setText("CMND");

        jLabel15.setText("Lớp");

      

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("thêm sinh viên");

        addSVBtn.setText("Thêm");
        addSVBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSVBtnActionPerformed(evt);
            }
        });

        comeback2.setText("Quay lại");
        /*comeback2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comeback2MouseClicked(evt);
            }
        });*/
        comeback2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeback2ActionPerformed(evt);
            }
        });
        comeback4.setText("Quay lại");
        /*comeback2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comeback2MouseClicked(evt);
            }
        });*/
        comeback4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comeback4aActionPerformed(evt);
            }
        });
        javax.swing.GroupLayout addSVpageLayout = new javax.swing.GroupLayout(addSVpage);
        addSVpage.setLayout(addSVpageLayout);
        addSVpageLayout.setHorizontalGroup(
            addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addSVpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addSVBtn)
                .addGap(185, 185, 185))
            .addGroup(addSVpageLayout.createSequentialGroup()
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addSVpageLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)))
                    .addComponent(comeback2))
                .addGap(64, 64, 64)
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2)
                    .addComponent(jTextField3)
                    .addComponent(jTextField4))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        addSVpageLayout.setVerticalGroup(
            addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addSVpageLayout.createSequentialGroup()
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addSVpageLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comeback2))
                .addGap(18, 18, 18)
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addSVpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addSVBtn)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 458, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainpage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(changePasswordpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchClasspage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Schedulepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addSVpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(importpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchGradepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SVPKpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PKpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchSVGradepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))	
        		);
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(loginpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainpage2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(changePasswordpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(searchClasspage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(Schedulepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(addSVpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(importpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            		.addGap(0, 0, Short.MAX_VALUE)
            		.addComponent(searchGradepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SVPKpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(PKpage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchSVGradepage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        		);
        
        PKpage.setVisible(false);
        mainpage.setVisible(false);
        mainpage2.setVisible(false);
       searchClasspage.setVisible(false);
       Schedulepage.setVisible(false);
        changePasswordpage.setVisible(false);
        //jPanel1.setVisible(false);
        addSVpage.setVisible(false);
        filePath.setVisible(false);
        importpage.setVisible(false);
        searchGradepage.setVisible(false);
        SVPKpage.setVisible(false);
        searchSVGradepage.setVisible(false);
        pack();
        
    }// </editor-fold>                        

    protected void comeback9ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	staticsticpage.setVisible(false);
    	getMainPage();
	}
	protected void comeback8ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	searchSVGradepage.setVisible(false);
    	getMainPage();
		
	}
	protected void searchSVGradeActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
	Grade gp;
	try {
	gp = temp.c10(user,subJectSearchFIeld.getText());
     	//JTable table = new JTable(new DefaultTableModel(new Object[]{"Column1", "Column2"}));
     	DefaultTableModel tbl = (DefaultTableModel) watchGrade.getModel();
     	
     	
     	
     		svClassroomId idKey = gp.getidKey(); 
     		
     		  tbl.addRow(new Object[]{gp.getId(), idKey.getMssv().getMssv(),
     				  idKey.getMssv().getName(),gp.getMidterm(),gp.getFinalTerm()
     				  ,gp.getOtherPoint(),gp.getTotal()});
     		
	}
	catch(NullPointerException e)
	{
		JOptionPane.showMessageDialog(null, "Chưa có điểm hoặc bạn không học lớp này");
	}
		
	}
	protected void comeback7ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	PKpage.setVisible(false);
    	getMainPage();
		
	}
	protected void pkBtnActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	try
    	{
    	String name = NameField.getText();
    	String MSSV = MssvField.getText();
    	String column = pointField.getText();
    	String subject = subjectField.getText();
    	String reasons = reason.getText();
    	float wantedPoint = Float.valueOf(wantedPointField.getText());
    	pk PK = new pk(MSSV,name,subject,column,wantedPoint,reasons);
    	SVcheck.addPK(PK);
    	JOptionPane.showMessageDialog(null,"Gửi đơn phúc khảo thành công");
    	}catch(Exception e)
    	{
    		JOptionPane.showMessageDialog(null,"Đã xảy ra lỗi, vui lòng thử lại");
    		e.printStackTrace();
    	}
		
	}
	protected void comeback6ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	SVPKpage.setVisible(false);
    	getMainPage();
		
	}
	protected void GradeWatchActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	mainpage.setVisible(false);
    	searchGradepage.setVisible(true);
		
	}
	protected void searchClassGradeActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		Classroom cl = temp.getClassInfo( classField3.getText());
     	Set<Grade> gplist = cl.getGradeList();
     	//JTable table = new JTable(new DefaultTableModel(new Object[]{"Column1", "Column2"}));
     	DefaultTableModel tbl = (DefaultTableModel) watchGrade.getModel();
     	
     	int count = 0;
     	for(Grade gp:gplist)
     	{	
     		svClassroomId idKey = gp.getidKey(); 
     		
     		  tbl.addRow(new Object[]{gp.getId(), idKey.getMssv().getMssv(),
     				  idKey.getMssv().getName(),gp.getMidterm(),gp.getFinalTerm()
     				  ,gp.getOtherPoint(),gp.getTotal()});
     		
     		
     	} 
		
	}
	protected void comeback5ActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	searchGradepage.setVisible(false);
    	getMainPage();
	}
	protected void comeback4aActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	importpage.setVisible(false);
    	getMainPage();
	}

	protected void confirmFileChoiceActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	String choice = chooseImport.getSelectedItem().toString();
    	String path ;
    	StringBuffer tempPath= new StringBuffer(filePath.getSelectedFile().toString());
    	path = tempPath.toString();
    	
    	//System.out.println( filePath.getSelectedFile().toString());
    	try {
    	if(tempPath!=null)
    	{
    	Classroom cl = new Classroom();
    	for(int i = 0; i < tempPath.length(); i++)
    	{	
    		if(tempPath.charAt(i)=='\\')
    			{
    				tempPath.insert(i, '\\');
    				i++;
    			}
    				
    	}
    	//path = tempPath.toString();
    	//System.out.println(path);
    	SVcheck.choiceMake(choice, path);
    		}
    	JOptionPane.showMessageDialog(null, "Import thành công");
    	}
    	catch(NullPointerException e)
    	{
    		JOptionPane.showMessageDialog(null, "Import thất bại");
    		e.printStackTrace();
    		
    	}
		
	}

	protected void confirmChoiceActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
		filePath.setVisible(true);
    	if (filePath.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
    		  System.out.println("getCurrentDirectory(): " + filePath.getCurrentDirectory());
    		  System.out.println("getSelectedFile() : " + filePath.getSelectedFile());
    		} else {
    		  System.out.println("No Selection ");
    		}
		
	}

	protected void importListActionPerformed(ActionEvent evt) {
		// TODO Auto-generated method stub
    	mainpage.setVisible(false);
    	importpage.setVisible(true);
		
	}

	protected void changePassword1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
		
	}

	protected void comebackActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
		changePasswordpage.setVisible(false);
		getMainPage();
		
	}
	protected void comeback1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
		searchClasspage.setVisible(false);
		getMainPage();
		
	}
	protected void comeback2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
		addSVpage.setVisible(false);
		getMainPage();
		
	}
	protected void comeback3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
		Schedulepage.setVisible(false);
		getMainPage();
		
	}
	protected void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
    	  mainpage.setVisible(false);
    	  searchClasspage.setVisible(true);
		
	}

	

	

	/*private void passwordActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    	pwd = String.valueOf(password.getPassword());
    }                                               

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	
    	user = username.getText();
    	//user = username.nameField.getText();
    }      */                                     

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    	//user = null;
    	//pwd = null;
        mainpage.setVisible(false);
        mainpage2.setVisible(false);
        loginpage.setVisible(true);
    }                                      

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    	String st = username.getText();
    	user = username.getText();
    	pwd = String.valueOf(password.getPassword());
    	
    	System.out.println("st is: "+user);
    	System.out.println("st is: "+pwd);
			
	    	if(temp.checkAccount(user, pwd))
	    	{ loginpage.setVisible(false);
	    	getMainPage();
	    	}
	    	
	    	else
	    	{
	    		
	    		JOptionPane.showMessageDialog(null,"Sai tên đăng nhập hoặc mật khẩu");;
	    	}
		
    	
    	
        
    } 
    private void ScheduleWatchActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    	
    	mainpage.setVisible(false);
    	Schedulepage.setVisible(true);
    	
    }                                             

    private void staticsticActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	//mainpage.setVisible(false);
    	//Schedulepage.setVisible(true);
    	JOptionPane.showMessageDialog(null,"Chức năng đang bảo trì");
    }                                          

                            
    
                            

    private void confirmChangeMouseClicked(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    	String oldPass = oldPassword.getText();
    	String newPass = newPassword.getText();
    	String repeat = repeatNewPassword.getText();
    	System.out.println("Old password here "+oldPass);
    	if(oldPass.compareTo(pwd)==0)
    		{
    		if(newPass.compareTo(repeat)==0 && newPass!=null)
    			{
    			temp.changeAccountPassword(new Account(user,newPass));
    			JOptionPane.showMessageDialog(null,"Đổi mật khẩu thành công");
    			oldPassword.setText("");
    			newPassword.setText(null);
    			repeatNewPassword.setText(null);
    			changePasswordpage.setVisible(false);
    			getMainPage();
    			}
    		else
			{
    			JOptionPane.showMessageDialog(null,"Không trùng mật khẩu");
			}
    		}
    	else
    		{
    		JOptionPane.showMessageDialog(null,"Mật khẩu cũ sai");
    	}
    		
    	
    }                                          
                                   
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	mainpage.setVisible(false);
    	PKpage.setVisible(true);
    	List<pk> pkList= new ArrayList();
    	pkList = temp.getPKList();
    	DefaultTableModel tbl = (DefaultTableModel) jTable3.getModel();
    	for(pk PK:pkList)
     	{	
     		
     		
     		  tbl.addRow(new Object[]{PK.getId(), PK.getMssv(),
     				 PK.getName(),PK.getSubject(),PK.getColumn(),
     				 PK.getWantedPoint(),PK.getReason()});
     		
     		
     	} 
    	
    	
    }    
    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	mainpage.setVisible(false);
    	changePasswordpage.setVisible(true);
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	mainpage2.setVisible(false);
    	
    	searchSVGradepage.setVisible(true);
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	JOptionPane.showMessageDialog(null,"Chức năng đang bảo trì");
    }                                        

    /*private void classField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }   */                                        

    private void searchClassScheduleActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    	Classroom cl = temp.getClassInfo( classField2.getText());
     	Set<Schedule> sclist = cl.getScheduleList();
     	//JTable table = new JTable(new DefaultTableModel(new Object[]{"Column1", "Column2"}));
     	DefaultTableModel tbl = (DefaultTableModel) watchSchedule.getModel();
     	
     	
     	for(Schedule sc:sclist)
     	{	
     		
     		  tbl.addRow(new Object[]{sc.getId(), sc.getSubjectId().getsubjectId(), sc.getSubjectId().getName(), 
     				 sc.getRoom()});
     		
     	
     		
     	} 
    	
    }                                                   

    private void searchClassActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    	
     	Classroom cl = temp.getClassInfo( classField1.getText());
     	Set<SV>dssv = cl.getDSSV();
     	//JTable table = new JTable(new DefaultTableModel(new Object[]{"Column1", "Column2"}));
     	DefaultTableModel tbl = (DefaultTableModel) jTable2.getModel();
     	
     	
     	for(SV sv:dssv)
     	{	
     		
     		  tbl.addRow(new Object[]{sv.getId(), sv.getMssv(), sv.getName(), 
     				 sv.getGender(),sv.getCMND()});
     		
     		
     	
     		
     	}
    }                                           

  /*  private void classField2ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }   */                                        

                                          

    private void addSVBtnActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	String mssv = jTextField1.getText();
    	String name = jTextField2.getText();
    	String CMND = jTextField3.getText();
    	
    	Classroom cl = temp.getClassInfo(jTextField4.getText());
    	if(cl ==null)
    		{
    			JOptionPane.showMessageDialog(null, "Lớp không tồn tại");
    			return;
    		}
    		
    	
    	SV sv = new SV(mssv,name,null,CMND);
    	sv.addClassroom(cl);
    	temp.addSV(sv);
    	JOptionPane.showMessageDialog(null, "Thêm sinh viên thành công");
    	
    }                                        

    private void addSVActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    	mainpage.setVisible(false);
    	addSVpage.setVisible(true);
    }                                     

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    	mainpage2.setVisible(false);
    	SVPKpage.setVisible(true);
    }
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    public String getUser() {
		return user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	public String getPsw() {
		return pwd;
	}

	public void setPsw(String pwd) {
		this.pwd = pwd;
	}

	// Variables declaration - do not modify                     
	private javax.swing.JButton ScheduleWatch;
    private javax.swing.JPanel Schedulepage;
    private javax.swing.JButton addSV;
    private javax.swing.JButton addSVBtn;
    private javax.swing.JPanel addSVpage;
    private javax.swing.JButton changePassword;
    private javax.swing.JButton changePassword1;
    private javax.swing.JPanel changePasswordpage;
    private javax.swing.JTextField classField1;
    private javax.swing.JTextField classField2;
    private javax.swing.JButton comeback;
    private javax.swing.JButton comeback1;
    private javax.swing.JButton comeback2;
    private javax.swing.JButton comeback3;
    private javax.swing.JButton comeback4;
    private javax.swing.JButton comeback5;
    private javax.swing.JButton confirmChange;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton login;
    private javax.swing.JPanel loginpage;
    private javax.swing.JButton logout;
    private javax.swing.JButton logout1;
    private javax.swing.JPanel mainpage;
    private javax.swing.JPanel mainpage2;
    private javax.swing.JTextField newPassword;
    private javax.swing.JTextField oldPassword;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField repeatNewPassword;
    private javax.swing.JButton searchClass;
    private javax.swing.JButton searchClassSchedule;
    private javax.swing.JButton searchGrade;
    private javax.swing.JPanel searchClasspage;
    private javax.swing.JButton staticstic;
    private javax.swing.JTextField username;
    private javax.swing.JTable watchSchedule;
    private javax.swing.JComboBox<String> chooseImport;
    private javax.swing.JButton confirmChoice;
    private javax.swing.JButton confirmFileChoice;
    private javax.swing.JFileChooser filePath;
    private javax.swing.JButton importList;
    private javax.swing.JButton GradeWatch;
    private javax.swing.JPanel importpage;
    private javax.swing.JTextField classField3;
    
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton searchClassGrade;
    private javax.swing.JPanel searchGradepage;
    private javax.swing.JTable watchGrade;
    private javax.swing.JTextField NameField;
    private javax.swing.JPanel SVPKpage;
    private javax.swing.JButton comeback6;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JTextField MssvField;
    private javax.swing.JButton pkBtn;
    private javax.swing.JTextField pointField;
    private javax.swing.JTextField reason;
    private javax.swing.JTextField subjectField;
    private javax.swing.JTextField wantedPointField;
    private javax.swing.JPanel PKpage;
    private javax.swing.JButton comeback7;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton comeback8;
    private javax.swing.JLabel jLabelM;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton searchSVGrade;
    private javax.swing.JPanel searchSVGradepage;
    private javax.swing.JTextField subJectSearchFIeld;
    private javax.swing.JTable watchGradeSV;
    private javax.swing.JButton comeback9;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable4;
    private javax.swing.JPanel staticsticpage;
    // End of variables declaration                   
}
